databases:
  - name: s-url
    ipAllowList: []
    databaseName: s_url_production
    user: s_url_production

services:
  - type: web
    name: my_app_render
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: s_url_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false