databases:
  - name: postgres
    ipAllowList: []
    databaseName: s_url
    user: s_url

services:
  - type: web
    name: s_url
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false